# Generated by Django 4.1.7 on 2023-03-22 13:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_entered", models.DateTimeField(auto_now_add=True)),
                (
                    "commenter_name",
                    models.CharField(blank=True, max_length=127, null=True),
                ),
                ("comment_text", models.CharField(max_length=255)),
                (
                    "manual_positivity_rating",
                    models.SmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "auto_positivity_rating",
                    models.SmallIntegerField(blank=True, null=True),
                ),
                ("ok_to_display", models.BooleanField(default=True)),
                ("auto_is_spam", models.BooleanField(default=False)),
                ("manual_is_spam", models.BooleanField(default=False)),
                (
                    "parent_comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="comments.comment",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_entered"],
            },
        ),
    ]
