# Generated by Django 3.2.7 on 2021-09-19 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todolist',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
