# Generated by Django 3.2.7 on 2021-09-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210919_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
