# Generated by Django 3.2.7 on 2021-09-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todoitem_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='date_completed',
            field=models.DateTimeField(null=True),
        ),
    ]
