# Generated by Django 3.2.7 on 2021-09-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_todoitem_date_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
