# Generated by Django 3.2.8 on 2021-10-13 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_rename_completed_todoitem_complete'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={'ordering': ['-priority', 'name']},
        ),
        migrations.AddField(
            model_name='todolist',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Normal'), (3, 'High')], default=2),
        ),
    ]
