# Generated by Django 4.1.4 on 2022-12-25 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameMapProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=127, null=True)),
                ('read_12_description', models.CharField(max_length=100)),
                ('read_23_description', models.CharField(max_length=100)),
                ('read_31_description', models.CharField(max_length=100)),
                ('read_121_option', models.CharField(max_length=100)),
                ('read_122_option', models.CharField(max_length=100)),
                ('read_232_option', models.CharField(max_length=100)),
                ('read_233_option', models.CharField(max_length=100)),
                ('read_311_option', models.CharField(max_length=100)),
                ('read_312_option', models.CharField(max_length=100)),
                ('play_1', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_pos_1', to='Game_Map.position')),
                ('play_2', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_pos_2', to='Game_Map.position')),
                ('play_3', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_pos_3', to='Game_Map.position')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='Game_Map.gamemapprofile')),
            ],
        ),
    ]
