# Generated by Django 4.1.4 on 2022-12-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game_Map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='read_121_option',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='position',
            name='read_122_option',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='position',
            name='read_12_description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='position',
            name='read_232_option',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='position',
            name='read_233_option',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='position',
            name='read_23_description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='position',
            name='read_311_option',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='position',
            name='read_312_option',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='position',
            name='read_31_description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
