# Generated by Django 4.1.4 on 2022-12-25 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Game_Map', '0002_alter_position_read_121_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='play_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_pos_1', to='Game_Map.position'),
        ),
        migrations.AlterField(
            model_name='position',
            name='play_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_pos_2', to='Game_Map.position'),
        ),
        migrations.AlterField(
            model_name='position',
            name='play_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_pos_3', to='Game_Map.position'),
        ),
    ]
