# Generated by Django 4.1.4 on 2022-12-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game_Map', '0003_alter_position_play_1_alter_position_play_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='initial',
            field=models.BooleanField(default=False),
        ),
    ]
