# Generated by Django 4.1.4 on 2022-12-25 18:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Game_Map', '0004_position_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GameMapProfile',
            new_name='Profile',
        ),
    ]
