# Generated by Django 4.1.4 on 2022-12-26 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Game_Map', '0005_rename_gamemapprofile_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='read_312_option',
            new_name='read_313_option',
        ),
    ]
