# Generated by Django 4.1.7 on 2023-03-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("live_chat_webRTC", "0003_alter_room_answer_alter_room_offer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="offer",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
