# Generated by Django 4.1.7 on 2023-03-17 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("live_chat_webRTC", "0004_alter_room_offer"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="invitee_email",
            field=models.EmailField(default="dave@daveisthebest.com", max_length=254),
            preserve_default=False,
        ),
    ]
