# Generated by Django 4.1.4 on 2023-01-16 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("file_sharing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sharedfile",
            name="file",
            field=models.FileField(upload_to="file_sharing/"),
        ),
        migrations.CreateModel(
            name="AccessEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=70)),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_emails",
                        to="file_sharing.sharedfile",
                    ),
                ),
            ],
        ),
    ]
