# Generated by Django 4.1.4 on 2023-01-16 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("file_sharing", "0002_alter_sharedfile_file_accessemail"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sharedfile",
            old_name="file_name",
            new_name="description",
        ),
    ]
