# Generated by Django 4.1.4 on 2023-01-16 21:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("file_sharing", "0003_rename_file_name_sharedfile_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="sharedfile",
            name="date_uploaded",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
