# Generated by Django 4.1.4 on 2023-01-21 12:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("file_sharing", "0004_sharedfile_date_uploaded"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessemail",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
