# Generated by Django 4.1.4 on 2023-02-04 01:04

from django.db import migrations, models
import file_sharing.validators


class Migration(migrations.Migration):

    dependencies = [
        ("file_sharing", "0005_alter_accessemail_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sharedfile",
            name="file",
            field=models.FileField(
                upload_to="file_sharing/",
                validators=[file_sharing.validators.validate_file_size],
            ),
        ),
    ]
