# Generated by Django 3.2.8 on 2022-06-04 14:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entered', models.DateTimeField(auto_now_add=True)),
                ('commenter_name', models.CharField(blank=True, max_length=127, null=True)),
                ('comment_text', models.CharField(max_length=255)),
                ('manual_positivity_rating', models.SmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('auto_positivity_rating', models.SmallIntegerField(null=True)),
            ],
        ),
    ]
