# Generated by Django 3.2.8 on 2022-06-04 14:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DaveIsTheBest_base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='auto_positivity_rating',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='manual_positivity_rating',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
