# Generated by Django 3.2.8 on 2022-06-26 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DaveIsTheBest_base', '0002_auto_20220604_0911'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['date_entered']},
        ),
        migrations.AddField(
            model_name='comment',
            name='ok_to_display',
            field=models.BooleanField(default=False),
        ),
    ]
