# Generated by Django 3.2.8 on 2022-06-26 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DaveIsTheBest_base', '0003_auto_20220626_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='ok_to_display',
            field=models.BooleanField(default=True),
        ),
    ]
