# Generated by Django 4.0.5 on 2022-07-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DaveIsTheBest_base', '0005_alter_comment_options_comment_is_spam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='is_spam',
            new_name='auto_is_spam',
        ),
        migrations.AddField(
            model_name='comment',
            name='manual_is_spam',
            field=models.BooleanField(default=False),
        ),
    ]
