# Generated by Django 4.1.4 on 2022-12-27 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DaveIsTheBest_base', '0006_rename_is_spam_comment_auto_is_spam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='DaveIsTheBest_base.comment'),
        ),
    ]
