# Generated by Django 4.1.7 on 2023-03-22 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("DaveIsTheBest_base", "0008_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
